services:

  mysql_database_newspaper:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secure
      MYSQL_DATABASE: newspaper
    ports:
      - 3306:3306
  cache_newspaper:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass secure
    volumes:
      - newspaper_redis_cache:/data

  persistence_web_ui:
    image: rediscommander/redis-commander:latest
    depends_on:
      - cache_newspaper 
    environment:
      REDIS_HOSTS: cache_newspaper 
      REDIS_HOST: cache_newspaper 
      REDIS_PORT: cache_newspaper:6379
      REDIS_PASSWORD: secure
      HTTP_USER: admin
      HTTP_PASSWORD: admin
    ports:
      - 8081:8081
volumes:
  newspaper_redis_cache:
    driver: local

